model:
  num_iteration: 200
  num_epoch: 200
  learning_rate: 0.001
  batch_size: 64
  momentum: 0.1

dataset:
  data_flags: ['octmnist', 'organamnist', 'tissuemnist']
  num_channels: 1
  amount: 8000
  valid_ratio: 0.1
  test_ratio: 0.2
